### ISSUE TITLE
 BitmapFactory.decodeStream(...) called twice

### ISSUE THREAD

**Issue by TannerS** [Clarifai/clarifai-android-starter#1]
Was it intentionally, to have

 BitmapFactory.decodeStream(getContentResolver().openInputStream(uri), null, opts);

called twice within the private Bitmap loadBitmapFromUri(Uri uri) method 

it is used to return a Bitmap which is why it is returned such as 

return BitmapFactory.decodeStream(getContentResolver().openInputStream(uri), null, opts);

but it is also called in the method without returning or assigning it to anything, was this a typo or intentionally?

**Comment by keithito** [comment]
Hi Tanner,

This is intentional. The first call passes an Options object with inJustDecodeBounds set to true. This causes the BitmapFactory to retrieve the dimensions without decoding the bitmap. In the following lines, these dimensions are used to compute a sampleSize to load an image that is approximately the same size as the screen.

For more info, please see the Android docs linked to in the comment just above this code:
http://developer.android.com/training/displaying-bitmaps/load-bitmap.html
